name: Binary

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: "Binary (via nuitka)"
      run: |
        pip install .
        pip install nuitka
        make bin

    - name: "Run & tests"
      run: |
        file ./mxf-reader
        ldd ./mxf-reader
        ./mxf-reader -f tests/assets/2D.mxf

    - name: 'Upload artifact'
      uses: actions/upload-artifact@v4
      with:
        name: mxf-reader
        path: mxf-reader
