name: Docker

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: 'Build Docker image'
      run: docker build -t mxf-reader:latest .

    - name: 'Test Docker image'
      run: docker run -v "$(pwd)/tests/assets:/assets" --rm mxf-reader:latest -f /assets/2D.mxf

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
      permissions:
        contents: read
        packages: write
    - name: 'Push Docker image'
      run: |
        docker tag mxf-reader:latest ghcr.io/sherpadown/mxf-reader:latest
        docker push ghcr.io/sherpadown/mxf-reader:latest
